import { createClient } from "jsr:@supabase/supabase-js@2";
const supabaseUrl=Deno.env.get("SUPABASE_URL")!;
const serviceKey=Deno.env.get(["SUPABASE","SECRET_KEY"].join("_"))||Deno.env.get(["SUPABASE","SERVICE","ROLE_KEY"].join("_"))!;
const admin=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});
const headers={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type, accept","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer","Permissions-Policy":"camera=(), microphone=(), geolocation=()"};
const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers});
function clean(v:unknown,max:number){if(typeof v!=="string")return"";return Array.from(v.normalize("NFC").replace(/\r\n?/g,"\n").replace(/[\u0000-\u001f\u007f\u200b-\u200f\u202a-\u202e\u2060\u2066-\u2069]/g,"").trim()).slice(0,max).join("")}
function validRoom(v:string){return/^[A-Za-z0-9_-]{8,32}$/.test(v)}
function abusive(v:string){const c=[...v];if(c.length<32)return false;const symbols=c.filter(x=>/[^\p{L}\p{N}\s.,!?;:'"()_\-]/u.test(x)).length;return v.split("\n").length>4||symbols/c.length>.42||/(.)\1{14,}/u.test(v)}
function clientIp(req:Request){return req.headers.get("cf-connecting-ip")?.trim()||req.headers.get("x-real-ip")?.trim()||req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown"}
async function digest(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function limit(key:string,max:number,seconds:number){const{data,error}=await admin.rpc("check_rate_limit",{p_key:key,p_max:max,p_window_seconds:seconds});if(error)throw error;return data===true}
async function prune(){if(Math.random()<.04)await admin.rpc("prune_chat_data")}
async function get(req:Request){const u=new URL(req.url),room=clean(u.searchParams.get("room"),32),after=clean(u.searchParams.get("after"),40);if(!validRoom(room))return response({error:"Sala inválida."},400);let q=admin.from("chat_messages").select("id,room_id,client_id,name,content,created_at").eq("room_id",room).gt("expires_at",new Date().toISOString()).order("created_at",{ascending:true}).limit(100);if(after&&/^\d{4}-\d{2}-\d{2}T/.test(after))q=q.gt("created_at",after);const{data,error}=await q;if(error)return response({error:"Não foi possível carregar a sala."},500);return response({messages:data||[]})}
async function post(req:Request){const length=Number(req.headers.get("content-length")||0);if(length>12000)return response({error:"Requisição muito grande."},413);const ip=await digest(clientIp(req)+":public-chat-v2"),body=await req.json().catch(()=>null);if(!body||typeof body!=="object")return response({error:"JSON inválido."},400);const s=body as Record<string,unknown>,room=clean(s.room,32),name=clean(s.name,24),message=clean(s.message,200),clientId=clean(s.clientId,80);if(!validRoom(room)||!name||!message||!clientId)return response({error:"Dados inválidos."},400);if([...message].length>200)return response({error:"A mensagem deve ter no máximo 200 caracteres."},400);if(abusive(message))return response({error:"Mensagem bloqueada por excesso de símbolos ou repetição."},422);if(/(?:https?:\/\/|www\.)/i.test(message))return response({error:"Links não são permitidos."},422);if(!(await limit(await digest(`${ip}:${room}`),8,10))||!(await limit(await digest(`${ip}:global`),60,60)))return response({error:"Você está enviando rápido demais. Espere alguns segundos."},429);const{data,error}=await admin.from("chat_messages").insert({room_id:room,client_id:clientId,name,content:message}).select("id,room_id,client_id,name,content,created_at").single();if(error||!data)return response({error:"Não foi possível enviar a mensagem."},500);await prune();return response({message:data})}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers});try{if(req.method==="GET")return await get(req);if(req.method==="POST")return await post(req);return response({error:"Método não permitido."},405)}catch{return response({error:"Erro interno."},500)}});
